# Site settings

author: Le Coiffeur
email: LeCoiffeur@selagemcapilar.github.io
youtube_channel:  null
youtube_username:  null
github_username:  null
twitter_username: null
googleplus_username: null

head-title: Selagem Capilar - Tudo o que você precisa saber está aqui!
title: Selagem Capilar
description: ""

baseurl: ""    # the subpath of your site, "/blog"
url: "https://selagemcapilar.github.io"

#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji, jekyll-sitemap]

#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

